### ISSUE TITLE
Error Creating Docker Image Following Automation and Build Server Setup Guide

### ISSUE THREAD

**Issue by NwJo01** [br-automation-com/BnR-DevOps-Package#10]
Hi @wesleybuchanan 

I've been following the guide for setting up an automation and build server as outlined in the PowerPoint presentation. However, I encounter an error every time I attempt to create a Docker image. I've attached the error message for reference. Could my location in Europe be influencing this issue?
Thank you for your assistance.

![screengrabb](https://github.com/br-automation-com/BnR-DevOps-Package/assets/157484045/f280ce46-8011-45b4-b935-c741537ba476)

**Comment by wesleybuchanan** [comment]
Hi @NwJo01 

Is the Dockerfile in the same directory that you are running the command from?  From the screenshot it looks like you are running the command from your Downloads folder.  I'd recommend moving all the needed files (Dockerfile, AS installation  directory, etc) for the docker image to a separate folder and run the command from there.  When creating the docker image the entire folder is sent to the docker engine and if there are files that aren't needed in your Download directory this will slow down the creation of the image.

I don't believe that you running in Europe should have any influence on this.

**Comment by NwJo01** [comment]
Hello @wesleybuchanan 

I've successfully built the Docker Image. Thanks for your assistance!
