### ISSUE TITLE
.gitignore not working

### ISSUE THREAD

**Issue by Dualton** [br-automation-com/BnR-DevOps-Package#2]
had to remove a couple of backslashes from .gitignore to make it work in my setup:

/AS/System/
/Binaries/
/Diagnosis/
/Temp/
/*.isopen

to

AS/System/
Binaries/
Diagnosis/
Temp/
*.isopen

otherwise files would not be ignored. am I missing something or is there an error in your .gitignore?

**Comment by wesleybuchanan** [comment]
Hi @Dualton, 
Our .gitignore file is meant to be placed in the Automation Studio project's directory, the same directory that contains the Logical and Physical folders.  
![image](https://github.com/br-automation-com/BnR-DevOps-Package/assets/27431013/a1329b5c-b4a9-4fbb-980a-3bc54032c93d)

The / at the beginning of the line makes it so only those directories in the Automation Studio project's directory would be ignored.  For example a folder Logical/Temp would **not** be ignored with our .gitignore file but would be with your changes.  

You can also find more information on the .gitignore rules at https://www.atlassian.com/git/tutorials/saving-changes/gitignore#git-ignore-patterns

**Comment by Dualton** [comment]
Ah, my fault! Had .gitignore stored in root but AS project stored in a sub folder.

Thanks!
