### ISSUE TITLE
Why should jenkins be set up on Windows?

### ISSUE THREAD

**Issue by Dualton** [br-automation-com/BnR-DevOps-Package#4]
I am supposed to use a Jenkins agent anyways. Can't I just install Jenkins on Linux and use a windows agent for Build and tasks?

**Comment by wesleybuchanan** [comment]
Hi Dualton, yes you could install Jenkins on linux and separately set up a Jenkins agent running on Windows for building the Automation Studio project and any other tasks that require Windows (such as running the unit tests on ArSim).

**Comment by Dualton** [comment]
Thanks!
